export enum SuitState {
  RETIRADO = 'RETIRADO',
  ENLOCALLMPIO = 'ENLOCALLIMPIO',
  LAVANDERIASUCIO = 'LAVANDERIASUCIO',
  LAVANDERIALIMPIO = 'LAVANDERIALIMPIO',
  MODISTA = 'MODISTA',
  ENLOCALSUCIO = 'ENLOCALSUCIO',
}
export enum SuitCategory {
  A = 'A',
  B = 'B',
  C = 'C',
  D = 'D',
  E = 'E',
}
